name: Restart Pterodactyl on push

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ptero-restart
  cancel-in-progress: true

jobs:
  restart:
    runs-on: ubuntu-latest
    env:
      RAW_BASE:         ${{ secrets.PTERO_BASE_URL }}
      PTERO_API_KEY:    ${{ secrets.PTERO_API_KEY }}
      PTERO_SERVER_ID:  ${{ secrets.PTERO_SERVER_ID }}
    steps:
      - name: Normalize base
        id: norm
        run: |
          set -euo pipefail
          BASE="${RAW_BASE%/}"           # strip trailing slash
          BASE="${BASE%/api}"            # strip accidental /api
          BASE="${BASE%/panel}"          # strip accidental /panel
          echo "BASE=$BASE" >> "$GITHUB_ENV"
          echo "ID=$PTERO_SERVER_ID" >> "$GITHUB_ENV"
          # print just the host (not the secret) for sanity
          echo "Using host: $(echo "$BASE" | sed -E 's#https?://([^/]+).*#\1#')"

      - name: Preflight (best-effort) — list servers
        continue-on-error: true
        run: |
          set -euo pipefail
          echo "GET $BASE/api/client/servers"
          curl -sS -o /tmp/servers.json -w "HTTP %{http_code}\n" \
            -H "Authorization: Bearer $PTERO_API_KEY" \
            -H "Accept: application/json" \
            "$BASE/api/client/servers" | tee /tmp/preflight.status
          if grep -q "HTTP 2" /tmp/preflight.status; then
            jq '.data[].attributes | {identifier,name}' /tmp/servers.json || true
          else
            echo "::warning::Preflight did not return 2xx (continuing anyway)"
            head -c 200 /tmp/servers.json || true; echo
          fi

      - name: Restart server via Client API
        run: |
          set -euo pipefail
          for SIGNAL in restart start; do
            echo "Sending $SIGNAL to $ID ..."
            HTTP_CODE=$(curl -sS -o /tmp/resp.txt -w "%{http_code}" \
              -X POST "$BASE/api/client/servers/$ID/power" \
              -H "Authorization: Bearer $PTERO_API_KEY" \
              -H "Content-Type: application/json" \
              -H "Accept: application/json" \
              --data "{\"signal\":\"$SIGNAL\"}")
            echo "HTTP $HTTP_CODE"
            cat /tmp/resp.txt || true
            if [ "$HTTP_CODE" -ge 200 ] && [ "$HTTP_CODE" -lt 300 ]; then
              echo "Power $SIGNAL accepted."
              exit 0
            fi
          done
          echo "Power requests failed. See response above."
          exit 1

